// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Noter.Inrastructure.Persistence.DbContexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Noter.Inrastructure.Migrations
{
    [DbContext(typeof(NoterDbContext))]
    [Migration("20260617184453_UdateMilestons")]
    partial class UdateMilestons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Noter.Domain.Entities.DbEntities.LearningTimer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StoppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LearningTimers");
                });

            modelBuilder.Entity("Noter.Domain.Entities.DbEntities.Milestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MonthlyPlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudyGoalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MonthlyPlanId");

                    b.HasIndex("StudyGoalId");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("Noter.Domain.Entities.DbEntities.MonthlyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudyPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MonthlyPlans");
                });

            modelBuilder.Entity("Noter.Domain.Entities.DbEntities.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReminderTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("Noter.Domain.Entities.DbEntities.StudyGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("StudyGoals");
                });

            modelBuilder.Entity("Noter.Domain.Entities.DbEntities.StudySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("StudySessions");
                });

            modelBuilder.Entity("Noter.Domain.Entities.DbEntities.StudySessionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MilestoneId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlannedMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlannedStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MilestoneId");

                    b.ToTable("StudySessionPlans");
                });

            modelBuilder.Entity("Noter.Domain.Entities.DbEntities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Noter.Domain.Entities.DbEntities.Milestone", b =>
                {
                    b.HasOne("Noter.Domain.Entities.DbEntities.MonthlyPlan", null)
                        .WithMany("Milestones")
                        .HasForeignKey("MonthlyPlanId");

                    b.HasOne("Noter.Domain.Entities.DbEntities.StudyGoal", null)
                        .WithMany("Milestones")
                        .HasForeignKey("StudyGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Noter.Domain.Entities.DbEntities.StudyGoal", b =>
                {
                    b.HasOne("Noter.Domain.Entities.DbEntities.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Noter.Domain.Entities.DbEntities.StudySessionPlan", b =>
                {
                    b.HasOne("Noter.Domain.Entities.DbEntities.MonthlyPlan", null)
                        .WithMany("Sessions")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Noter.Domain.Entities.DbEntities.Milestone", null)
                        .WithMany("StudySessionPlans")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Noter.Domain.Entities.DbEntities.Milestone", b =>
                {
                    b.Navigation("StudySessionPlans");
                });

            modelBuilder.Entity("Noter.Domain.Entities.DbEntities.MonthlyPlan", b =>
                {
                    b.Navigation("Milestones");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Noter.Domain.Entities.DbEntities.StudyGoal", b =>
                {
                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("Noter.Domain.Entities.DbEntities.User", b =>
                {
                    b.Navigation("Goals");
                });
#pragma warning restore 612, 618
        }
    }
}
